# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget peloton peloton-proto pg_query peloton-capnp)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target peloton
add_library(peloton SHARED IMPORTED)

# Create imported target peloton-proto
add_library(peloton-proto STATIC IMPORTED)

# Create imported target pg_query
add_library(pg_query STATIC IMPORTED)

# Create imported target peloton-capnp
add_library(peloton-capnp STATIC IMPORTED)

# Import target "peloton" for configuration "Debug"
set_property(TARGET peloton APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(peloton PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "peloton-proto;peloton-capnp;/usr/local/lib/libboost_system-mt.dylib;/usr/local/lib/libboost_filesystem-mt.dylib;/usr/local/lib/libboost_thread-mt.dylib;/usr/local/lib/libboost_chrono-mt.dylib;/usr/local/lib/libboost_date_time-mt.dylib;/usr/local/lib/libboost_atomic-mt.dylib;/usr/local/lib/libgflags.dylib;/Users/Alpha/Documents/s18/15721/peloton/testbuild/external/capnp-install/lib/libcapnp-rpc.a;/Users/Alpha/Documents/s18/15721/peloton/testbuild/external/capnp-install/lib/libcapnp.a;/Users/Alpha/Documents/s18/15721/peloton/testbuild/external/capnp-install/lib/libkj-async.a;/Users/Alpha/Documents/s18/15721/peloton/testbuild/external/capnp-install/lib/libkj.a;/usr/local/lib/libprotobuf.dylib;/usr/local/lib/libevent.dylib;/usr/local/lib/libevent_pthreads.dylib;/usr/local/lib/libpqxx.dylib;/usr/local/lib/libpq.dylib;-lssl -lcrypto;LLVMCore;LLVMMCJIT;LLVMX86CodeGen;LLVMX86Desc;LLVMX86Info;LLVMX86CodeGen;LLVMX86AsmPrinter;LLVMX86AsmParser;LLVMX86Desc;LLVMX86Info;LLVMX86Disassembler;peloton-proto;pg_query"
  IMPORTED_LOCATION_DEBUG "/Users/Alpha/Documents/s18/15721/peloton/testbuild/lib/libpeloton-d.0.0.5.dylib"
  IMPORTED_SONAME_DEBUG "@rpath/libpeloton-d.0.0.5.dylib"
  )

# Import target "peloton-proto" for configuration "Debug"
set_property(TARGET peloton-proto APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(peloton-proto PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Alpha/Documents/s18/15721/peloton/testbuild/lib/libpeloton-proto-d.a"
  )

# Import target "pg_query" for configuration "Debug"
set_property(TARGET pg_query APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(pg_query PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/Alpha/Documents/s18/15721/peloton/testbuild/lib/libpg_query.a"
  )

# Import target "peloton-capnp" for configuration "Debug"
set_property(TARGET peloton-capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(peloton-capnp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Alpha/Documents/s18/15721/peloton/testbuild/lib/libpeloton-capnp-d.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
